Algoritmo "LacoDeRepeticaoPara"
// Disciplina   : Linguagem de Programação com JavaScript
// Professor   : Jailson
// Descrição   : Conta de 1 até 10
// Autor(a)    : Gislaine Vasconcelos Guimarães
// Data atual  : 31/03/2023
Var
// Seção de Declarações das variáveis 
contadora:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 para contadora de 1 ate 10 passo 1 faca
 Escreval(contadora)
 fimpara

Fimalgoritmo